# -*- coding: utf-8 -*-

# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDrightNOTAND AUTHOR CONTENT LINK LPAREN MINUS NOT OR PLUS RPAREN TITLE WORDfilter : expressionexpression : ruleexpression : expression AND expressionexpression : expression OR expressionexpression : NOT expressionexpression : LPAREN expression RPARENrule : type qualifier WORDtype : PLUS\n            | MINUS\n            | emptyqualifier : TITLE \n                 | LINK \n                 | AUTHOR \n                 | CONTENT\n                 | emptyempty :'

_lr_action_items = {'NOT': ([0, 4, 5, 10, 11, ], [4, 4, 4, 4, 4, ]), 'LPAREN': ([0, 4, 5, 10, 11, ], [5, 5, 5, 5, 5, ]), 'PLUS': ([0, 4, 5, 10, 11, ], [7, 7, 7, 7, 7, ]), 'MINUS': ([0, 4, 5, 10, 11, ], [8, 8, 8, 8, 8, ]), 'TITLE': ([0, 4, 5, 6, 7, 8, 9, 10, 11, ], [-16, -16, -16, 15, -8, -9, -10, -16, -16, ]), 'LINK': ([0, 4, 5, 6, 7, 8, 9, 10, 11, ], [-16, -16, -16, 16, -8, -9, -10, -16, -16, ]), 'AUTHOR': ([0, 4, 5, 6, 7, 8, 9, 10, 11, ], [-16, -16, -16, 17, -8, -9, -10, -16, -16, ]), 'CONTENT': ([0, 4, 5, 6, 7,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         8, 9, 10, 11, ], [-16, -16, -16, 18, -8, -9, -10, -16, -16, ]), 'WORD': ([0, 4, 5, 6, 7, 8, 9, 10, 11, 14, 15, 16, 17, 18, 19, ], [-16, -16, -16, -16, -8, -9, -10, -16, -16, 23, -11, -12, -13, -14, -15, ]), '$end': ([1, 2, 3, 12, 20, 21, 22, 23, ], [0, -1, -2, -5, -3, -4, -6, -7, ]), 'AND': ([2, 3, 12, 13, 20, 21, 22, 23, ], [10, -2, -5, 10, -3, 10, -6, -7, ]), 'OR': ([2, 3, 12, 13, 20, 21, 22, 23, ], [11, -2, -5, 11, -3, -4, -6, -7, ]), 'RPAREN': ([3, 12, 13, 20, 21, 22, 23, ], [-2, -5, 22, -3, -4, -6, -7, ]), }

_lr_action = {}
for _k, _v in _lr_action_items.items():
    for _x, _y in zip(_v[0], _v[1]):
        if not _x in _lr_action:
            _lr_action[_x] = {}
        _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'filter': ([0, ], [1, ]), 'expression': ([0, 4, 5, 10, 11, ], [2, 12, 13, 20, 21, ]), 'rule': ([0, 4, 5, 10, 11, ], [3, 3, 3, 3, 3, ]), 'type': (
    [0, 4, 5, 10, 11, ], [6, 6, 6, 6, 6, ]), 'empty': ([0, 4, 5, 6, 10, 11, ], [9, 9, 9, 19, 9, 9, ]), 'qualifier': ([6, ], [14, ]), }

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
    for _x, _y in zip(_v[0], _v[1]):
        if not _x in _lr_goto:
            _lr_goto[_x] = {}
        _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
    ("S' -> filter", "S'", 1, None, None, None),
    ('filter -> expression', 'filter', 1, 'p_filter', 'filters.py', 162),
    ('expression -> rule', 'expression', 1,
     'p_expression_rule', 'filters.py', 166),
    ('expression -> expression AND expression',
        'expression', 3, 'p_expression_and', 'filters.py', 170),
    ('expression -> expression OR expression',
        'expression', 3, 'p_expression_or', 'filters.py', 174),
    ('expression -> NOT expression', 'expression',
        2, 'p_expression_not', 'filters.py', 178),
    ('expression -> LPAREN expression RPAREN', 'expression',
        3, 'p_expression_group', 'filters.py', 182),
    ('rule -> type qualifier WORD', 'rule', 3, 'p_rule', 'filters.py', 186),
    ('type -> PLUS', 'type', 1, 'p_type', 'filters.py', 190),
    ('type -> MINUS', 'type', 1, 'p_type', 'filters.py', 191),
    ('type -> empty', 'type', 1, 'p_type', 'filters.py', 192),
    ('qualifier -> TITLE', 'qualifier', 1, 'p_qualifier', 'filters.py', 196),
    ('qualifier -> LINK', 'qualifier', 1, 'p_qualifier', 'filters.py', 197),
    ('qualifier -> AUTHOR', 'qualifier', 1, 'p_qualifier', 'filters.py', 198),
    ('qualifier -> CONTENT', 'qualifier', 1, 'p_qualifier', 'filters.py', 199),
    ('qualifier -> empty', 'qualifier', 1, 'p_qualifier', 'filters.py', 200),
    ('empty -> <empty>', 'empty', 0, 'p_empty', 'filters.py', 204),
]
